### ISSUE TITLE
Walletconnect 4001 Reject Session

### ISSUE THREAD

**Issue by LS20221** [tronprotocol/tronwallet-adapter#14]
I have been trying to connect via walletconnect to the tron network with no avail for some time now. I get error 4001 Reject Session, using the following code in vanilla JS.

async function onConnect() {
	const web3Modal = new Web3Modal.Web3Modal({
	  projectId: MY_PROJECT_ID,
	  // `standaloneChains` can also be specified when calling `web3Modal.openModal(...)` later on.
	  standaloneChains: ['tron:0x2b6653dc'],
	});
	
	const SignClient = window['@walletconnect/sign-client'].SignClient;
	const wcModal = window.WalletConnectQRCodeModal;
    const signClient = await SignClient.init({
        projectId: MY_PROJECT_ID,
        relayUrl: 'wss://relay.walletconnect.com',
        metadata: {
        name: "Example Dapp",
        description: "Example Dapp",
        url: "#",
        icons: ["https://walletconnect.com/walletconnect-logo.png"],
        },
    });
    try {
        const { uri, approval } = await signClient.connect({
            /*requiredNamespaces: {
                eip155: {
                  methods: [
                    "eth_sendTransaction",
                    "eth_signTransaction",
                    "eth_sign",
                    "personal_sign",
                    "eth_signTypedData",
                  ],
                  chains: ["eip155:1", "eip155:100"],
                  events: ["chainChanged", "accountsChanged"],
                },
              },*/
            requiredNamespaces: {
                tron: {
                    methods: ['tron_signTransaction', 'tron_signMessage'],
                    chains: ['tron:0x2b6653dc'],
                    events: [],
                },
            }
        });
        if (uri) {
			web3Modal.openModal({ uri });
			// Await session approval from the wallet.
			const session = await approval();
			// Handle the returned session (e.g. update UI to "connected" state).
			// * You will need to create this function *
			console.log(session);
			// Close the QRCode modal in case it was open.
			web3Modal.closeModal();
            /*wcModal.default.open(uri, () => {
            console.log('error en la conexion');
			wcModal.default.close();
            });
            const session = await approval();
            console.log(session)
            wcModal.default.close();*/
        }

    } catch (e) {
        console.error(e);

    }
}

window.addEventListener('load', async () => {
  console.log(window)
  document.querySelector("#boton").addEventListener("click", onConnect);
});

Any help would be appreciate it. Using the same code but for eip networks everything worls perfectly, so the walletconnect and web3Modal libraries are working ok.

The versions of the libraries are:

walletconnect 2.4.4
web3modal 2.1.1 (stand alone)

Im trying to connect to trsut wallet.

**Comment by way2ex** [comment]
Hi~ Does the wallet you want to connect support tron?

**Comment by LS20221** [comment]
Hi, yeah is trust wallet

**Comment by way2ex** [comment]
I have try using trust wallet app, but it will throw an error. 
It seems that trust wallet doesn't support tron yet.
You can use this wallet to test your client code: https://github.com/WalletConnect/web-examples/tree/main/wallets/react-wallet-v2

**Comment by LS20221** [comment]
Ok, thanks. Thats bad cause I need it for commercial use, so I need popular wallets to work with tron, but I guess nothing I can do then.
