### ISSUE TITLE
Why I can't transfer USDT trc20 without private key?

### ISSUE THREAD

**Issue by deantek** [tronprotocol/tronwallet-adapter#16]
I took your example, I send tron ​​like this and everything works through tronLink and walletConnect

````
export const tronWeb: any = new TronWeb({
    fullHost: 'https://api.trongrid.io',
    headers: {
      'TRON-PRO-API-KEY': "my-api-key", 
      'Content-Type': 'application/json'
    },
});

    async function onSignTransaction() {
        if (address) {
            const transaction = await tronWeb.transactionBuilder.sendTrx(receiver, tronWeb.toSun(1), address);
            console.log('transaction', transaction);

            const signedTransaction = await signTransaction(transaction);

            console.log('signedTransaction', signedTransaction)
            const res = await tronWeb.trx.sendRawTransaction(signedTransaction);
            console.log('res', res)
            setOpen(true)
            setTxId(res.txid)
        }
    }
````

i do it without private key and everything works, but why when i try to send USDT from one address to another i need private key?

this doesn`t work

````
 async function sendUSDT() {
        let contract = await tronWeb.contract().at('TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t')
        console.log('contract', contract)
        let result = await contract.methods.transfer(receiver, 1).send()
        console.log('res', result)
    }
````
Is it possible to send USDT from one address to another without a private key?
I'm trying to make a dapp, with EVM and TVM networks, but I'm stuck at this point

**Comment by way2ex** [comment]
hi, when you initiate tronWeb instance, you can pass a `privateKey`:
```
const tronWeb = new TronWeb({
  fullHost: 'https://api.trongrid.io',
  headers: { 'TRON-PRO-API-KEY': 'your api key' },
  privateKey: 'your private key'
});
```
when you call `tronWeb.trx.sign()`, if you omit the privateKey, tronWeb will use your privateKey when you create `tronWeb` instance.

So when you  trigger the  contract to send USDT you must provide a private key.

But when you use TronLink or other wallets, these wallets will inject a `tronWeb` instance on `window` so you can use `window.tronWeb.trx.sign()` to sign a transaction.
And as these wallets manage your wallet accounts, they also can obtain your privateKey internally. So you can use `window.tronWeb.trx.sign()` without privateKey to sign a transaction.

WalletAdapter use `window.tronWeb` to sign a transaction so there is no need to provide `privateKey`.

If you used your tronWeb but `window.tronWeb` you must provide `privateKey`. This is not recommended. Just use `window.tronWeb`.

**Comment by deantek** [comment]
@zhuqingguang Hello, thanks, I was able to call the transaction signing via tronLink via window.tronWeb, but when I connect via WalletConnect, it will not work, could you tell me if it is also possible to sign the transaction from the mobile wallet without using the private key?

**Comment by way2ex** [comment]
When you want to use walletconnect on mobile to sign the transaction, you can not use `tronWeb.trx.sign()` because `window.tronWeb` has no relation with your mobile wallet account.

You can use WalletconnectAdapter to sign:
```typescript
import { WalletconnectAdapter } from '@tronweb3/tronwallet-adapter-walletconnect';

const walletconnectAdapter = new WalletconnectAdapter({
// your config
});
await walletconnectAdapter.connect();
const functionSelector = 'transfer(address,uint256)';
const parameter = [{type:'address',value:'receiver address'},{type:'uint256',value:100}]
const tx = await tronWeb.transactionBuilder.triggerSmartContract('TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t', functionSelector, {}, parameter);
const signedTx = await walletconnectAdapter.sign(tx.transaction);
const result = await tronWeb.trx.sendRawTransaction(signedTx);
```
You can find more API information for [TronwalletAdapter](https://developers.tron.network/docs/tronwallet-adapter#walletconnectadapter) and [TronWeb trigger contract](https://tronweb.network/docu/docs/Interact%20with%20contract#triggersmartcontract).

Do not use `tronWeb.contract.at()` because in this way you can not sign with mobile wallet.

**Comment by deantek** [comment]
@zhuqingguang, 
thanks, i did it, its works

````
    async function sendUSDT() {
        if (isWalletConnect) {
            const walletconnectAdapter = wallet?.adapter
            if (walletconnectAdapter) {
                const functionSelector = 'transfer(address,uint256)';
                const parameter = [{type:'address',value: receiver},{type:'uint256',value:1000}]
                const tx = await tronWeb.transactionBuilder.triggerSmartContract('TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t', functionSelector, {
                    feeLimit: 1_000_000,
                    callValue: tronWeb.toSun(0.1)
                }, parameter, address);
                console.log('tx', tx)
                //@ts-ignore
                const signedTx = await walletconnectAdapter.signTransaction(tx.transaction);
                console.log('signedTx', signedTx)
                const result = await tronWeb.trx.sendRawTransaction(signedTx);
                console.log('result', result)
                setOpen(true)
                setTxId(result.txid)
            }
        }
        //@ts-ignore
        if (window.tronWeb && !isWalletConnect) {
            //@ts-ignore
            let contract = await window.tronWeb.contract().at('TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t')
            console.log('contract', contract)
            let result = await contract.methods.transfer(receiver, tronWeb.toSun(0.1)).send()
            console.log('res', result)
            setOpen(true)
            setTxId(result.txid)
        }
    }   
````

**Comment by areddyacqrx** [comment]
@deantek Thanks for explaining how to transfer TRC20 tokens from mobile and web wallets. I have correctly implemented the transfer from the web wallet(tron link) but when I try to transfer from the trust wallet mobile wallet, in the confirmation screen I am seeing my ETH wallet address. Can you please let me know where I am doing wrong?

This is my wallet connector config:
`
  const adapters = useMemo(function () {
    const walletConnectAdapter = new WalletConnectAdapter({
      network: "Mainnet",
      options: {
        relayUrl: "wss://relay.walletconnect.com",
        projectId: "****",
        metadata: {
          name: "Test DApp",
          description: "JustLend WalletConnect",
          url: "https://your-dapp-url.org/",
          icons: ["https://your-dapp-url.org/mainLogo.svg"]
        }
      }
    });
    return [
      walletConnectAdapter
    ];
  }, []);
`


And this is my transfer request function:

`
  async function onSignTransaction() {
    const functionSelector = "transfer(address,uint256)";
    const parameter = [
      { type: "address", value: receiver },
      { type: "uint256", value: 1000 }
    ];
    const tx = await tronWeb.transactionBuilder.triggerSmartContract(
      "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t",
      functionSelector,
      {
        callValue: tronWeb.toSun(0.1)
      },
      parameter,
      address
    );
    console.log("tx", tx);
    const signedTx = await signTransaction(tx.transaction);
    console.log("signedTx", signedTx);
    const result = await tronWeb.trx.sendRawTransaction(signedTx);
    console.log("result", result);
  }
`

![IMG_1452](https://github.com/tronprotocol/tronwallet-adapter/assets/72747133/8acf7462-e19c-4ea9-9ebb-fbf3378b67a0)
