### ISSUE TITLE
Transfer confirm on mobile wallet using walletconnect shows ethereum address

### ISSUE THREAD

**Issue by areddyacqrx** [tronprotocol/tronwallet-adapter#20]
Hi, 

I am trying to connect DAPP with trustwallet mobile app using walletconnect. I am used the demo app provided by tronwallet-adapter here https://github.com/tronprotocol/tronwallet-adapter/tree/main/demos/react-ui/create-react-app.

I tested connecting my trustwallet with the walletconnect qr code shown and the connection was successfull. When I tried to transfer TRC to the receiver address, I get a confirmation notification on my trustwallet app. But I see details are incorrect there. It is showing my ethereum wallet address in `From` field. 

Is the details shown in confirm screen correct? Can somebody please tell me what I am doing wrong? 

This is my wallet connector config
`       
 const walletConnectAdapter = new WalletConnectAdapter({
            network: 'Mainnet',
            options: {
                relayUrl: 'wss://relay.walletconnect.com',
                // example WC app project ID
                projectId: '****',
                metadata: {
                    name: 'Test DApp',
                    description: 'JustLend WalletConnect',
                    url: 'https://your-dapp-url.org/',
                    icons: ['https://your-dapp-url.org/mainLogo.svg'],
                },
            },
        });
`

Below is the screenshot of what I am seeing on mobile. 

![IMG_1452](https://github.com/tronprotocol/tronwallet-adapter/assets/72747133/63d4fad5-7e1a-4d72-8a33-91fc0b939f24)

**Comment by way2ex** [comment]
Have you change the selected wallet to Tron BlockChain?

**Comment by Cancass** [comment]
> Hi,
> 
> I am trying to connect DAPP with trustwallet mobile app using walletconnect. I am used the demo app provided by tronwallet-adapter here https://github.com/tronprotocol/tronwallet-adapter/tree/main/demos/react-ui/create-react-app.
> 
> I tested connecting my trustwallet with the walletconnect qr code shown and the connection was successfull. When I tried to transfer TRC to the receiver address, I get a confirmation notification on my trustwallet app. But I see details are incorrect there. It is showing my ethereum wallet address in `From` field.
> 
> Is the details shown in confirm screen correct? Can somebody please tell me what I am doing wrong?
> 
> This is my wallet connector config ` const walletConnectAdapter = new WalletConnectAdapter({ network: 'Mainnet', options: { relayUrl: 'wss://relay.walletconnect.com', // example WC app project ID projectId: '****', metadata: { name: 'Test DApp', description: 'JustLend WalletConnect', url: 'https://your-dapp-url.org/', icons: ['https://your-dapp-url.org/mainLogo.svg'], }, }, });`
> 
> Below is the screenshot of what I am seeing on mobile.
> 
> ![IMG_1452](https://user-images.githubusercontent.com/72747133/245362977-63d4fad5-7e1a-4d72-8a33-91fc0b939f24.PNG)

Hello @areddyacqrx,
Have you resolve this issue?
