### ISSUE TITLE
Has walletconnect been supported yet? 

### ISSUE THREAD

**Issue by qixiaobro** [tronprotocol/tronwallet-adapter#23]
Hi, I tested using the official @tronweb3/tronwallet-adapters demo and when I tried to open it with imToken, it said that this network is not supported yet.

**Comment by way2ex** [comment]
`wallet-adapter-walletconnect` supports WalletConnect but imToken can  not connect Tron network with walletconnect according to [this article](https://token.im/blog/en-us/articles/16022224934809-imToken-2-11-3-now-supports-WalletConnect-2-0?locale=en-us)

**Comment by qixiaobro** [comment]
Do you know which wallets support Tron? Thank you.

**Comment by unicornonea** [comment]
Hi, currently Fireblocks Wallet supports the walletconnect protocol of TRON network. For other wallets such as TronLink, we are promoting support. It's our pleasure to notify you if there is any progress.

**Comment by qixiaobro** [comment]
close this issure

**Comment by way2ex** [comment]
I have tried the latest Bitkeep on IOS with this [Example](https://react-app.walletconnect.com/) and it supports connect to TRON wallet with WalletConnect. Just scan the WalletConnect QRCode with BitKeep.
