### ISSUE TITLE
Init connection event sequence exception

### ISSUE THREAD

**Issue by xiaoai7904** [tronprotocol/tronwallet-adapter#24]
<img width="745" alt="image" src="https://github.com/tronprotocol/tronwallet-adapter/assets/40415469/66918f8d-a435-4b77-98bf-5f201b997e98">

<img width="487" alt="image" src="https://github.com/tronprotocol/tronwallet-adapter/assets/40415469/388ac0f2-3624-4fc5-8819-0d2628c4a771">

<img width="903" alt="image" src="https://github.com/tronprotocol/tronwallet-adapter/assets/40415469/e3ac2285-9d52-41bf-aac4-aa2b64488d6b">

<img width="364" alt="image" src="https://github.com/tronprotocol/tronwallet-adapter/assets/40415469/5c77c136-24b2-48e1-81c3-07d3c79cb9f2">

 "@tronweb3/tronwallet-adapter-react-hooks": "^1.1.4",
  "@tronweb3/tronwallet-adapter-react-ui": "^1.1.5",
  "@tronweb3/tronwallet-adapters": "^1.1.6"
    
Clear the cache and initialize the connection exception for the first time
The wallet is successfully connected, but the disconnect event will be triggered at the end, and the address will be assigned a null value, resulting in an abnormal page display

**Comment by pdazcom** [comment]
+1
same problem without using react

**Comment by way2ex** [comment]
`disconnect` event is triggered when TronLink emits `accountsChanged` with empty accounts. It seems that TronLink extension has changed their events.
Does the bug occurs in production ? We can publish a hot fix if necessary.

**Comment by pdazcom** [comment]
yes, the error appeared after updating the tronLink extension. fixes are needed. thank you!

**Comment by alienzhangyw** [comment]
+1, `accountsChanged` and `disconnect` are triggered after `connect`.

**Comment by way2ex** [comment]
Sorry for any inconvenience. `v1.1.8` has fixed this error.

**Comment by lytieuphong** [comment]
v1.1.8 still not fixed

**Comment by way2ex** [comment]
> v1.1.8 still not fixed

I have checked  the adapter with the latest TronLink extension(v4.1.3) and it work fine. When i first call `adapter.connect()` , it will not disconnect then. Could you please describe the detail of the bug? Thank you!

**Comment by lytieuphong** [comment]
Sure, Here is my code:
@tronweb3/tronwallet-adapters@1.1.8
tronlink extension v4.1.3
```ts
    const tronLinkAdapter = new TronLinkAdapter();
    let address = "";
    let chainId = 0;

    await tronLinkAdapter.connect();

    if (tronLinkAdapter.address) {
      address = tronLinkAdapter.address;
      try {
        const network = await tronLinkAdapter.network(); // call this will throw issue
        chainId = parseInt(network.chainId);
      } catch (e) {
    // catch error here
      }
    }
```
1. Connect success 
2. Lock wallet from Tron Link extension
3. Reload Dapp then click connect to TronLink

Error message:
`WalletDisconnectedError: The wallet is disconnected. Please connect first.`

Adapter object:
```js
{
_readyState: "Found",
_state: "Connected"
}
```

Note that It just happen for some times, not always.

Thank you

**Comment by way2ex** [comment]
It seems that TronLink has an issue that when first connect to TronLink, `window.tron.tronWeb` is not available immediately. `setTimeout` should work fine. 
 `network()` method depends `window.tron.tronWeb` to get network information. So error occurs.
![image](https://github.com/tronprotocol/tronwallet-adapter/assets/24694223/fbdcf7e3-f3eb-406f-81ba-fae8f8b14dbf)

You can use the following code when `tron.tronWeb` is available.
```js
 const chainIdNetworkMap = {
    '0x2b6653dc': 'Mainnet',
    '0x94a9059e': 'Shasta',
    '0xcd8690dc': 'Nile',
};

async function getNetworkInfo() {
    const tronWeb = window.tron.tronWeb;
    const { blockID = '' } = await tronWeb.trx.getBlockByNumber(0);
    const chainId = `0x${blockID.slice(-8)}`;
    return {
        networkType: chainIdNetworkMap[chainId],
        chainId,
        fullNode: tronWeb.fullNode?.host || '',
        solidityNode: tronWeb.solidityNode?.host || '',
        eventServer: tronWeb.eventServer?.host || '',
    };
}
```
