### ISSUE TITLE
How to get current connected chainId?

### ISSUE THREAD

**Issue by alienzhangyw** [tronprotocol/tronwallet-adapter#28]
How can I get the chain id inside WalletProvider?
How can I change chain inside WalletProvider?

**Comment by way2ex** [comment]
`useWallet()` hook will return an object containing a `wallet` property and you can use it to get `adapter`:

```typescript
const { wallet } = useWallet();
if (wallet) {
   const { chainId } = await wallet.adapter.network();
}
```

You can switch chain using `switchChain(chainId)`
```js
const { wallet } = useWallet();
if (wallet) {
   const { chainId } = await wallet.adapter.switchChain('0xcd8690dc');
}
```

Available chainIds:
     - Mainnet: 0x2b6653dc
     - Shasta: 0x94a9059e
     - Nile: 0xcd8690dc
     
`switchChain()` is only supported by TronLink extension.

**Comment by alienzhangyw** [comment]
> `useWallet()` hook will return an object containing a `wallet` property and you can use it to get `adapter`:
> 
> ```ts
> const { wallet } = useWallet();
> if (wallet) {
>    const { chainId } = await wallet.adapter.network();
> }
> ```
> 
> You can switch chain using `switchChain(chainId)`
> 
> ```js
> const { wallet } = useWallet();
> if (wallet) {
>    const { chainId } = await wallet.adapter.switchChain('0xcd8690dc');
> }
> ```
> 
> Available chainIds: - Mainnet: 0x2b6653dc - Shasta: 0x94a9059e - Nile: 0xcd8690dc
> 
> `switchChain()` is only supported by TronLink extension.

I found this before. But you don't have the ts definition in Adapter class, so I overwrited it:
```typescript
import { TronLinkAdapter } from '@tronweb3/tronwallet-adapters';
import { Adapter } from '@tronweb3/tronwallet-abstract-adapter';
interface MyAdapter extends Adapter {
  network?: TronLinkAdapter['network'];
}
```
