### ISSUE TITLE
调用USDT合约transfer方法时候弹出的签名界面和正常转账弹出的界面不一致。

### ISSUE THREAD

**Issue by jcai** [tronprotocol/tronwallet-adapter#29]
调用transfer API的时候弹出界面：

<img width="360" alt="image" src="https://github.com/tronprotocol/tronwallet-adapter/assets/6152/df3bbe34-3466-4864-a9aa-16cbdf867827">

和正常转账弹出界面不一样。

```ts
      const functionSelector = 'transfer(address,uint256)';
      var options = {
        feeLimit:100000000,
      };
      const parameter = [{type:'address',value:receiver},{type:'uint256',value:100}]

      const tx = await tronWeb.transactionBuilder.triggerSmartContract(CONTRACT, functionSelector, options, parameter,address);
      const signedTx = await wallet.adapter.signTransaction(tx.transaction);
      console.log("signedTx:",signedTx)
      const result = await tronWeb.trx.sendRawTransaction(signedTx);
      console.log("result:",result)
```

代码如上，签名之后，转账成功了，希望弹出签名界面和正常转账界面一致，不知道能否做到？

**Comment by jcai** [comment]
```ts
const tronWeb: any = new TronWeb({
    fullHost: MAIN_HOST,
});
```
```
window.tronWeb
```

这两个有啥区别，推荐用那个？第一种方式是demo里面的。如果使用window.tronweb就能正常显示签名

**Comment by jcai** [comment]
经过长时间的debug发现：`window.tronWeb.transactionBuilder.triggerSmartContract` 产生的交易对象里面有 `__payload__ `属性，而正常用 new TronWeb之后，产生的交易对象没有` __payload__`属性

**Comment by way2ex** [comment]
1. 签名页面的UI是TronLink插件控制的，API只是调用 `window.tronWeb.sign` 这个API，然后由插件进行响应。
2. `window.tronWeb` 是tron系钱包插件注入到全局的变量，内部保存了用户的账号的私钥，所以可以进行签名。如果自己使用 `new TronWeb()` 构建tronweb对象的话，需要设置私钥才能进行签名
   ```
       const tronWeb = new TronWeb({
            fullHost: 'https://api.trongrid.io',  
            headers: { 'TRON-PRO-API-KEY': 'your api key' },
            privateKey: 'your private key'
        });
   ```

**Comment by alienzhangyw** [comment]
如果需要使用window.tronWeb的话，那么使用adapter的意义何在？
我用adapter的目的不就是为了不直接使用window.tronWeb，而是用adapter.signTransaction来签名吗？

**Comment by way2ex** [comment]
> 如果需要使用window.tronWeb的话，那么使用adapter的意义何在？ 我用adapter的目的不就是为了不直接使用window.tronWeb，而是用adapter.signTransaction来签名吗？

adapter 的目的之一是为了屏蔽掉 window.tronWeb。这里只是阐述一下二者的区别以及插件弹窗出现所调用的底层API。`adapter.signTransaction` 底层也是调用 `window.tronWeb.sign`.

**Comment by jcai** [comment]
现在的问题是：
`window.tronWeb.transactionBuilder.triggerSmartContract` 产生的交易对象里面有 `__payload__ `属性，而正常用 new TronWeb之后，产生的交易对象没有` __payload__`属性，进而导致签名的界面不一样。
