### ISSUE TITLE
Cannot connect to TronLink app from mobile browser

### ISSUE THREAD

**Issue by alienzhangyw** [tronprotocol/tronwallet-adapter#30]
WalletNotFoundError: The wallet is not found.

**Comment by way2ex** [comment]
In mobile browser there is no `window.tronlink` so dapp must use [DeepLink](https://docs.tronlink.org/tronlink-app/deeplink/open-dapp) to invoke TronLink app if it exists in user's device.
If TronLink app is not installed, the DeepLink won't work and throw `WalletNotFoundError`.

**Comment by alienzhangyw** [comment]
> In mobile browser there is no `window.tronlink` so dapp must use [DeepLink](https://docs.tronlink.org/tronlink-app/deeplink/open-dapp) to invoke TronLink app if it exists in user's device. If TronLink app is not installed, the DeepLink won't work and throw `WalletNotFoundError`.

https://github.com/tronprotocol/tronwallet-adapter/blob/eaaac80af7de46efe05620ee9b2cc173a804ca4c/packages/adapters/tronlink/src/utils.ts#L34-L47

The link that adapter generated can open the TronLink Pro android app, but it will crash within a second. May be the format is not right (The url don't have a protocol, and will append a `?_=1` param if my url don't have a hash.)?  You can test yourself with the react demo.

Then I generate the DeepLink by myself according to your doc:
```javascript
window.location.href = `tronlinkoutside://pull.activity?param=${encodeURIComponent(JSON.stringify({
        url: window.location.href,
        action: 'open',
        protocol: 'tronlink',
        version: '1.0',
      }))}`;
```
This works fine with the TronLink Global Android App, but not with the TronLink Pro Android App or the TronLink IOS App

**Comment by alienzhangyw** [comment]
我发现了问题所在，当我传给tronlink的url是
`https://payment.sandbox.utcpay.com/payment?apiSign=eXsALkECWDYcpCyw7h2kYpLbEZQo83YkHy9CfUHZ9iA%3D#?_=1`的时候苹果手机APP会报错：
![image](https://github.com/tronprotocol/tronwallet-adapter/assets/58874541/44380f07-f91d-4606-8bea-366a409672f6)
但是如果把域名host改成`sunswap.com`就不会报错了：（虽然打开的是404）
`https://sunswap.com/payment?apiSign=eXsALkECWDYcpCyw7h2kYpLbEZQo83YkHy9CfUHZ9iA%3D#?_=1`

难道TronLink对Dapp的域名有限制吗？需要在哪里认证吗？

**Comment by ismoli** [comment]
I have the same issue. According to your own docs at https://developers.tron.network/docs/tronwallet-adapter:

> Auto open TronLink app in mobile browser. If developers call connect() method in mobile browser, it will open DApp in TronLink app to get tronlink wallet.

This is not working, if Tronlink app on android is opened (in the background) and you call adapter.connect() it brings Tronlink app but then toast shows error and nothing happens.
If app is completely killed, and you call adapter.connect() it tries to open an app and it immediately crashes.

Im trying to achieve what seems like a simple and obvious and very useful flow: page displays button "pay with tronlink" , user clicks, app is opened with prefilled values for transaction (address, amount). 
This is working on desktop with Tronlink extension. However does not on mobile. The unified solution would be great as I can not support tens of different deeplinks for every wallet out there. For example your wallet-connect-tron also does not work reliably. Trust shows errors. This is really a mess, why there is no ONE unified protocol for opening wallets with some action like send tx that is prefilled?





> > In mobile browser there is no `window.tronlink` so dapp must use [DeepLink](https://docs.tronlink.org/tronlink-app/deeplink/open-dapp) to invoke TronLink app if it exists in user's device. If TronLink app is not installed, the DeepLink won't work and throw `WalletNotFoundError`.
> 
> https://github.com/tronprotocol/tronwallet-adapter/blob/eaaac80af7de46efe05620ee9b2cc173a804ca4c/packages/adapters/tronlink/src/utils.ts#L34-L47
> 
> The link that adapter generated can open the TronLink Pro android app, but it will crash within a second. May be the format is not right (The url don't have a protocol, and will append a `?_=1` param if my url don't have a hash.)? You can test yourself with the react demo.
> 
> Then I generate the DeepLink by myself according to your doc:
> 
> ```js
> window.location.href = `tronlinkoutside://pull.activity?param=${encodeURIComponent(JSON.stringify({
>         url: window.location.href,
>         action: 'open',
>         protocol: 'tronlink',
>         version: '1.0',
>       }))}`;
> ```
> 
> This works fine with the TronLink Global Android App, but not with the TronLink Pro Android App or the TronLink IOS App

**Comment by way2ex** [comment]
According to the [TronLink docs](https://docs.tronlink.org/tronlink-app/deeplink/open-dapp), adapter will construct the url when on mobile device. There may be some error with Android TronLink app. Could you please show your website url? Or you can construct the deeplink url by yourself according to the [deeplink docs](https://docs.tronlink.org/tronlink-app/deeplink/open-dapp).

**Comment by alienzhangyw** [comment]
> According to the [TronLink docs](https://docs.tronlink.org/tronlink-app/deeplink/open-dapp), adapter will construct the url when on mobile device. There may be some error with Android TronLink app. Could you please show your website url? Or you can construct the deeplink url by yourself according to the [deeplink docs](https://docs.tronlink.org/tronlink-app/deeplink/open-dapp).

Neither adapter generated link nor self-constructed deeplink works on  the TronLink Pro Android App or the TronLink IOS App.

@zhuqingguang  You can experience here: [Enter an email address and pay for this](https://payment.sandbox.utcpay.com/linkPay?apiSign=%2FVYSEZo4uyBI%2BAqkjouC5DjK7uZudnXgnVDSYiBj8Zg%3D) on Tron Nile.

**Comment by way2ex** [comment]
Sorry for any inconvenience. I have consult TronLink developer center and there indeed is a host whitelist.  To avoid malicious applications, dapp developers should apply permission of using deeplink for their website.
You can find a telegrame group link or email on the footer of [TronLink Homepage](https://www.tronlink.org/) . Thanks.
