### ISSUE TITLE
Use with vanilla js?

### ISSUE THREAD

**Issue by ismoli** [tronprotocol/tronwallet-adapter#32]
Hello, I would like to use this lib with vanilla js. Is that even possible? All documentation uses react/vue as examples. Do you plan to support it like wallet connect does?
So far found a way to import it using 
`import { TronLinkAdapter } from "https://cdn.jsdelivr.net/npm/@tronweb3/tronwallet-adapter-tronlink/+esm";`

it kinda works, except with walletconnect-adapter.
Also I have no idea if it possible to use WalletActionButton etc components? Any hints are appreciated!

**Comment by way2ex** [comment]
Yes, adapter can be used without vue/react.
```
import { TronLinkAdapter } from '@tronweb3/tronwallet-adapters';

// create an adapter instance
const adapter = new TronLinkAdapter();

// listen to events
adapter.on('accountsChanged', (address) => {
    console.log(address)
});

// connect wallet
await adapter.connect();

// sign transaction
adapter.sign('Your transaction')
```
You can find more detailed docs [here](https://developers.tron.network/docs/tronwallet-adapter#wallet-adapters)

**Comment by ismoli** [comment]
Unfortunately it does not work that way, very first line causes:

Uncaught TypeError: Failed to resolve module specifier "@tronweb3/tronwallet-adapters". Relative references must start with either "/", "./", or "../".

> Yes, adapter can be used without vue/react.
> 
> ```
> import { TronLinkAdapter } from '@tronweb3/tronwallet-adapters';
> 
> // create an adapter instance
> const adapter = new TronLinkAdapter();
> 
> // listen to events
> adapter.on('accountsChanged', (address) => {
>     console.log(address)
> });
> 
> // connect wallet
> await adapter.connect();
> 
> // sign transaction
> adapter.sign('Your transaction')
> ```
> 
> You can find more detailed docs [here](https://developers.tron.network/docs/tronwallet-adapter#wallet-adapters)

**Comment by way2ex** [comment]
Sorry for inconvenience. The adapter currently does not support to be used in a project without `npm` and bundlers like `webpack` or `vite`, because it has some other dependencies and does not provide a single `dist` file.
We will consider providing the ability next version.
