### ISSUE TITLE
`Web3Modal` has been upgraded to  `V3`，please adapt it

### ISSUE THREAD

**Issue by hhun** [tronprotocol/tronwallet-adapter#33]
`Web3Modal` 已经升级到 `V3`，请适配 `Web3Modal V3`
`Web3Modal` has been upgraded to  `V3`，please adapt it！

https://github.com/tronprotocol/tronwallet-adapter/tree/main/packages/adapters/walletconnect
https://www.npmjs.com/package/@tronweb3/walletconnect-tron
https://docs.walletconnect.com/web3modal/about

目前V2只适配`signTransaction`和`signMessage`方法，请适配下触发合约方法。
Currently V2 only adapts to the `signTransaction` and `signMessage` methods. Please adapt the trigger contract method.

**Comment by svein1010** [comment]
可否具体说明下您想要实现什么功能吗？Web3Modal 仅仅是提供选择钱包的弹窗UI，不涉及 signTransaction 以及 signMessage 等方法。

**Comment by hhun** [comment]
https://github.com/tronprotocol/tronwallet-adapter/tree/main/packages/adapters/walletconnect
里面只有`signTransaction`和`signMessage`演示，而且测试了下转账功能会报错。
能否增加`查询余额`、`估算gas`、`执行合约`的演示代码？

**Comment by hhun** [comment]
> 可否具体说明下您想要实现什么功能吗？Web3Modal 仅仅是提供选择钱包的弹窗UI，不涉及 signTransaction 以及 signMessage 等方法。

https://github.com/tronprotocol/tronwallet-adapter/tree/main/packages/adapters/walletconnect
里面只有`signTransaction`和`signMessage`演示，而且测试了下转账功能会报错。
能否增加`查询余额`、`估算gas`、`执行合约`的演示代码？

**Comment by hhun** [comment]
@svein1010 

https://github.com/tronprotocol/tronwallet-adapter/tree/main/demos/react-ui/vite-app

里面只有`signTransaction`和`signMessage`演示，而且我测试了下转账功能会报错。
能否增加`查询余额`、`估算转账所需Gas`、`估算写入合约所需Gas`、`读取合约`、`写入合约`的演示代码？

`Web3Modal V3`支持同时连接多个网络钱包，并且支持切换网络。

**Comment by svein1010** [comment]
Adapter 提供连接钱包的功能，并封装了钱包的签名功能。转账、查询余额、估算费用、与合约交互等功能不包含在adapter的功能范围内。这些需要开发者调用 tronweb 的 API 来实现。您可以阅读 [Tron的开发者指南](https://developers.tron.network/) 和 [tronweb 的开发者文档](https://tronweb.network/docu/docs/intro)。
下面是一些常用的API：
- [转账](https://tronweb.network/docu/docs/API%20List/transactionBuilder/sendTrx)
- [估算费用](https://tronweb.network/docu/docs/API%20List/transactionBuilder/estimateEnergy)
- [与合约交互](https://tronweb.network/docu/docs/API%20List/transactionBuilder/triggerSmartContract)
