### ISSUE TITLE
`WalletConnect` has been upgraded to `V3`，please adapt it

### ISSUE THREAD

**Issue by hhun** [tronprotocol/tronwallet-adapter#35]
`WalletConnect` 已经升级到 `V3`，请适配 Web3Modal V3
`WalletConnect` has been upgraded to `V3`，please adapt it！

`WalletConnect V3` 支持同时连接多个网络钱包，并且支持切换网络。
`WalletConnect V3` supports connecting to multiple network wallets at the same time, and supports switching networks.

**Comment by way2ex** [comment]
Thank you for your remind! We will consider updating it.

**Comment by ccingiz** [comment]
> `WalletConnect` 已经升级到 `V3`，请适配 Web3Modal V3
> `WalletConnect` has been upgraded to `V3`，please adapt it！
> 
> `WalletConnect V3` 支持同时连接多个网络钱包，并且支持切换网络。
> `WalletConnect V3` supports connecting to multiple network wallets at the same time, and supports switching networks.

**Comment by way2ex** [comment]
Currently，the `web3modal` does not support Tron blockChain. And the Walletconnect team will add support for Tron in the future. We will update it as soon as the new `web3modal` is published. Thanks for your attention!
