### ISSUE TITLE
Signature verification fail with WalletConnect

### ISSUE THREAD

**Issue by marcosteixeira** [tronprotocol/tronwallet-adapter#42]
In the dev-demo, React Hooks tab:

1) Change the adapter network to "Mainnet" (https://github.com/tronprotocol/tronwallet-adapter/blob/main/demos/dev-demo/src/ReactHooksDemo.tsx#L15). Otherwise Trust wallet won't connect.

2) Fix the onVerifyMessage function to use messageToSign as the first parameter. https://github.com/tronprotocol/tronwallet-adapter/blob/main/demos/dev-demo/src/ReactHooksDemo.tsx#L71

3) Connect with WalletConnect

4) Change the "Message to sign" to have more than 9 characters, otherwise it will fail. (not a real problem)

5) Sign and verify the message.

6) The addresses don't match.

**Comment by way2ex** [comment]
Hi~sorry for the inconvenience.  I have tried using Trust wallet on IOS v10.6 and Android v7.1 and it can connect but can not sign a message or a transaction. 

Please tell me the Android or ios version and I will check this function.

Also it's unclear that how trust wallet  sign the message.
Please try the following way:
```
tronWeb.trx.verifyMessage(tronWeb.toHex(messageToSign), signedMsg, address)
```

**Comment by way2ex** [comment]
Thank you for your attention. According to [Trust docs](https://developer.trustwallet.com/developer/develop-for-trust/mobile) Tron is not supported currently.
