### ISSUE TITLE
> .github/workflows/jekyll-gh-pages.yml102216dd96661d26a49d342e0c71035211a7cea9

### ISSUE THREAD

**Issue by ccingiz** [tronprotocol/tronwallet-adapter#45]
> .github/workflows/jekyll-gh-pages.yml102216dd96661d26a49d342e0c71035211a7cea9

_Originally posted by @ccingiz in https://github.com/tronprotocol/documentation/pull/487#issuecomment-1891143216_

**Comment by srbaeza-ai** [comment]
Complete

**Comment by srbaeza-ai** [comment]
https://github.com/tronprotocol/tronwallet-adapter/issues/45
