### ISSUE TITLE
NextJS project can't install @tronweb3/walletconnect-tron module

### ISSUE THREAD

**Issue by jeancarrie-kima** [tronprotocol/tronwallet-adapter#46]
I am using these modules on my NextJS project to have tron wallet integration

   ```
    "@tronweb3/tronwallet-abstract-adapter": "^1.1.0",
    "@tronweb3/tronwallet-adapter-ledger": "^1.1.1",
    "@tronweb3/tronwallet-adapter-react-hooks": "^1.0.0",
    "@tronweb3/tronwallet-adapters": "^1.1.1",
```

But getting `ERR_REQUIRE_ESM` error to use `@tronweb3/tronwallet-adapters`
![image](https://github.com/tronprotocol/tronwallet-adapter/assets/118423909/56240571-5c00-4435-b39b-ddbc96578996)

Please help me to fix this issue.

**Comment by way2ex** [comment]
The error "[ERR_REQUIRE_ESM]: require() of ES Module not supported. Instead change the require of index.js to a dynamic import() which is available in all CommonJS modules" occurs because a package you are importing has been converted to an ESM-only package, which means that the package cannot be imported with require() anymore.

Here you are using commonjs format of `@tronweb3/walletconnect-tron`, please check that if you are using `require('@tronweb3/tronwallet-adapters')` in your project. Instead change it to `import {} from '@tronweb3/tronwallet-adapters'`

**Comment by jeancarrie-kima** [comment]
`import {
  BitKeepAdapter,
  LedgerAdapter,
  OkxWalletAdapter,
  TokenPocketAdapter,
  TronLinkAdapter
} from '@tronweb3/tronwallet-adapters'`
I am using `import {}` not `require()`

**Comment by jeancarrie-kima** [comment]
@way2ex I am using `@tronweb3` module inside my npm module, and I used `microbundle-crl` to build the module.

`microbundle-crl --no-compress --format modern,es --css-modules false`

This is what I was using to build  my module and it could be the reason why `@tronweb3/tronwallet-adapters` is referenced by `required()`.
So I have changed the build command as `--format modern,es` to build as es module, but now I am getting different error.

![image](https://github.com/tronprotocol/tronwallet-adapter/assets/118423909/f39609a4-3f8e-4477-b131-755dbed8aaaa)

**Comment by way2ex** [comment]
It seems that you didn't export TronLinkAdapter correctly. Please check your configration. Some build tools will convert `import` to `require`. Also check your build target and ensure that it's ESM format.

**Comment by jeancarrie-kima** [comment]
@way2ex 
![image](https://github.com/tronprotocol/tronwallet-adapter/assets/118423909/a4efe487-459a-48ad-9da4-e79ba28c0063)
Here's my module structure, as you can see it builds in several formats - es and cjs.
Inside the module, I use only `import {}` for tron modules.

**Comment by way2ex** [comment]
Could you confirm that  which format of your npm package file nextjs is using ?  
Also you can try the following code to import TronLinkAdapter:
```
import { TronLinkAdapter } from '@tronweb3/tronwallet-adapters/lib/esm/index.js';
```

**Comment by jeancarrie-kima** [comment]
I will try your recommendation.
My nextjs project using `import {}` format to use my own module.

**Comment by jeancarrie-kima** [comment]
@way2ex Tried the way you recommended but here's the result.

![image](https://github.com/tronprotocol/tronwallet-adapter/assets/118423909/2d1ef291-c18b-4725-a30d-9c50e0ef5acf)

**Comment by way2ex** [comment]
Could you create a reproduce repository ?  I will fix it and commit in your repository.

**Comment by way2ex** [comment]
This way doesn't work for node esm. If you want to use TronLinkAdapter only, you can install the `@tronweb3/tronwallet-adapter-tronlink` and import from it:
```js
import { TronLinkAdapter } from '@tronweb3/tronwallet-adapter-tronlink'
```

**Comment by jeancarrie-kima** [comment]
@way2ex Thanks for your reply, I will prepare a repository for reproduce the issue. 
Please reach me out here, if you want to discuss in details.
https://t.me/jean_carrie

**Comment by jeancarrie-kima** [comment]
@way2ex I have created a repo for reproducing the issue.
Please check your invitation to this repo. 
https://github.com/jeancarrie-kima/kima-demo-ref

**Comment by jeancarrie-kima** [comment]
> This way doesn't work for node esm. If you want to use TronLinkAdapter only, you can install the `@tronweb3/tronwallet-adapter-tronlink` and import from it:
> 
> ```js
> import { TronLinkAdapter } from '@tronweb3/tronwallet-adapter-tronlink'
> ```
I am using several adapters that @tronweb3 module supports, not only tronlink.

**Comment by jeancarrie-kima** [comment]
@way2ex Thanks for your great support, really appreciate your advices.

In conclusion, I have replaced `@tronweb3/tronwallet-wallet-adapters` to `@tronweb3/tronwallet-wallet-tronlink` and other individual wallet adapter modules. This is the solution, 👍
