### ISSUE TITLE
OKX deeplink should use encodeURIComponent

### ISSUE THREAD

**Issue by alienzhangyw** [tronprotocol/tronwallet-adapter#47]
See OKX docs here https://www.okx.com/cn/web3/build/docs/sdks/app-universal-link#%E6%AD%A5%E9%AA%A4-2%EF%BC%9A%E7%BC%96%E7%A0%81-deeplink-%E5%8F%82%E6%95%B0

```javascript
const encodedDappUrl = encodeURIComponent(dappUrl);
const deepLink = "okx://wallet/dapp/url?dappUrl=" + encodedDappUrl;
```

In currenet version of OKX adapter, if these is any special character (%, +, etc) in dapp url, the link opened in OKX app's browser will be wrong.

**Comment by way2ex** [comment]
Thanks a lot for your remind. We will update the package soon.

**Comment by way2ex** [comment]
Hi, `v1.0.3` has been released. Please update the package version and check the deeplink functionality.

**Comment by alienzhangyw** [comment]
> Hi, `v1.0.3` has been released. Please update the package version and check the deeplink functionality.

Thanks, although we are not using this with OKX wallet now.
