### ISSUE TITLE
Experiencing issues with BitKeep connection

### ISSUE THREAD

**Issue by rharutyunyan-dev** [tronprotocol/tronwallet-adapter#51]
I'm trying to connect to my BitKeep Wallet from my React application. When my website is opened in the BitGet Wallet Browser, it redirects to the BitGet Wallet page, but then it freezes.

Here's the code I used for the connection:

```
const bitKeepAdapter = new BitKeepAdapter();
await bitKeepAdapter.connect();
```

I tried with iPhone 14

Could you please help me with this issue?

**Comment by way2ex** [comment]
It seems that Bitget Wallet App does not inject `window.tronWeb` or `window.tronLink` into browser which means that it doesn't support Tron Dapp currently. I will report the issue to Bitget Wallet Team and track this issue. Thanks a lot for your report.

**Comment by way2ex** [comment]
Hi~ Bitget Wallet `v8.12.0` for IOS is avaliable. Update your App and it should work fine. App on Android still doesn't work.

**Comment by rharutyunyan-dev** [comment]
> Hi~ Bitget Wallet `v8.12.0` for IOS is avaliable. Update your App and it should work fine. App on Android still doesn't work.

Thanks a lot, it worked!
