### ISSUE TITLE
@tronweb3/walletconnect-tron

### ISSUE THREAD

**Issue by kandrukKV** [tronprotocol/tronwallet-adapter#59]
Hello!

Can I access the source code repository for this package?

This package uses the @web3modal/standalone dependency inside itself, which does not work correctly when connected on mobile devices. I would like to change it to my package, but I can't find the source code for @tronweb3/walletconnect-tron.

**Comment by way2ex** [comment]
Hi，could you explain more detail about `does not work correctly when connected on mobile devices` ? 
When on mobile device, it should open a modal and others device could scan the QRCode to connect.

**Comment by kandrukKV** [comment]
You are absolutely right. 

But I use walletConnect together with Telegram Web App (TWA).

TWA blocks the opening of deep links, so I had to change @web3modal/standalone and change the opening of links.

By the way,  @web3modal/standalone is deprecated and I use @walletconnect/modal.

**Comment by way2ex** [comment]
Currently the source code of `@tronweb3/walletconnect-tron` has not been opened. You can view its code in your `node_modules` directory and the code is pretty simple.
We will consider to open the source code.

**Comment by kandrukKV** [comment]
Thank you. I will do so.
