### ISSUE TITLE
OkxWallet is not signed messages

### ISSUE THREAD

**Issue by Soures888** [tronprotocol/tronwallet-adapter#62]
<img width="651" alt="image" src="https://github.com/tronprotocol/tronwallet-adapter/assets/30728293/2e11214e-da21-4331-846d-5f9f0be0bb8a">

On sign message returning Q.match is not a function / Wallet is not found

**Comment by way2ex** [comment]
`adapter.signMessage()` use `tronWeb.trx.signMessageV2` and Okx Wallet does not support `tronWeb.trx.signMessageV2`. So `okxWalletAdapter.signMessage()` can not work fine with OKX wallet currently.

**Comment by Likang0122** [comment]
This problem still exists, how to solve it

**Comment by way2ex** [comment]
> This problem still exists, how to solve it

Okx Wallet does not support `tronWeb.trx.signMessageV2`.  You can use `window.okxwallet.tronLink.tronWeb.trx.sign(string)` to [sign a message](https://www.okx.com/web3/build/docs/sdks/chains/tron/provider#signing-messages)
