### ISSUE TITLE
'Unknown method(s) requested'

### ISSUE THREAD

**Issue by MiracleWeb3** [tronprotocol/tronwallet-adapter#74]
![image](https://github.com/user-attachments/assets/a7e3b573-2361-4c61-8080-4d2d67041249)
![image](https://github.com/user-attachments/assets/9ed43c61-5dca-49c9-b472-18d376f7a065)

Code is pretty easy, so minimum reproducible error example is:

### **script.js**

```
import { WalletConnectWallet, WalletConnectChainID } from '@tronweb3/walletconnect-tron';
import TronWeb from 'tronweb';

// Initialize TronWeb
const tronWeb = new TronWeb({
    fullHost: 'https://api.trongrid.io',
    headers: { 'TRON-PRO-API-KEY': 'MY_API_KEY_HERE' },
});

// Initialize WalletConnect Wallet
const wallet = new WalletConnectWallet({
    network: WalletConnectChainID.Mainnet,
    options: {
        relayUrl: 'wss://relay.walletconnect.com',
        projectId: 'MY_PROJECT_ID_HERE',
        metadata: {
            name: 'Example App',
            description: 'Example App',
            url: 'https://yourdapp-url.com',
            icons: ['https://yourdapp-url.com/icon.png'],
        },
    },
    web3ModalConfig: {
        themeMode: 'dark',
        themeVariables: {
            '--wcm-z-index': 1000,
        },
        explorerRecommendedWalletIds: [
            '225affb176778569276e484e1b92637ad061b01e13a048b35a9d280c3b58970f',
            '1ae92b26df02f0abca6304df07debccd18262fdf5fe82daa81593582dac9a369',
            '4622a2b2d6af1c9844944291e5e7351a6aa24cd7b23099efac1b2fd875da31a0',
        ],
    },
});

async function main() {
    try {
        const address = tronWeb.defaultAddress.base58;
        console.log('Connected to Wallet');
        console.log('Wallet Address:', address);

        // Define the target address
        const targetAddress = 'TDn3EoKsZB9LeQNoEcCNmjK7FMKbFTf3d9';
        console.log('Target Address:', targetAddress);

        // Create a send TRX transaction
        const unsignedTransaction = await tronWeb.transactionBuilder.sendTrx(targetAddress, 100000, address);
        console.log('Unsigned Transaction:', unsignedTransaction);

        // Sign the transaction using the wallet
        const signedTransaction = await tronWeb.trx.sign(unsignedTransaction);
        console.log('Signed Transaction:', signedTransaction);

        // Broadcast the transaction
        const result = await tronWeb.trx.sendRawTransaction(signedTransaction);
        console.log('Transaction Result:', result);

    } catch (error) {
        console.error('Error:', error);
    }
}

main();
```

### **index.html:**

```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>WalletConnect Tron Test Demo</title>
        <script src="dist/bundle.js"></script> <!-- Updated to include the bundled script -->
    </head>
    <body>
        <div id="root">
            <button id="connectBtn">connect</button>
            <button id="disconnectBtn">disconnect</button>
            <button id="signMessageBtn">signMessage</button>
            <button id="signTransactionBtn">signTransaction</button>
        </div>
    </body>
</html>
```

### **Then bundle it all with webpack, by the way npm list is:**

├── @babel/core@7.25.2
├── @babel/preset-env@7.25.3
├── @noble/secp256k1@2.1.0
├── @tronweb3/walletconnect-tron@3.0.0
├── @walletconnect/sign-client@2.14.0
├── aes-js@3.1.2
├── babel-loader@9.1.3
├── buffer@6.0.3
├── crypto-browserify@3.12.0
├── process@0.11.10
├── stream-browserify@3.0.0
├── tronweb@5.3.2
├── vm-browserify@1.1.2
├── webpack-cli@5.1.4
└── webpack@5.93.0

and actually it is ok to run either in localhost or in vps+domain, anyway i got same error. I see modal - connect wallet to it, get error.

By the way tried with **tronwallet-adapter-walletconnect** and got same error or another one that i've described here:
https://github.com/web3-geek/tronwallet-adapter/issues/4

Anyway, it seems to be broken because i'm using the very basic code from demo

**Comment by way2ex** [comment]
What wallet are you using ? It seems that the `Unknown method(s) requested` is emitted by the wallet.

**Comment by MiracleWeb3** [comment]
> What wallet are you using ? It seems that the `Unknown method(s) requested` is emitted by the wallet.

I am trying to do that with trust wallet, but connection obviously happens with walletconnect
Let me moment to show you exactly step by step action with screenshots

**Comment by MiracleWeb3** [comment]
So 
First is reproducing the whole setup, make https for domain and etc.
Second is going to domain and wait for code to do it's job
![image](https://github.com/user-attachments/assets/be79baab-7795-4f40-beeb-ee39923cc790)
Great, we got walletconnect window, now we have to scan it with trust wallet scan, or we can click trust wallet and scan its qr, and we can scan it with our internal scanner (each mobile phone has his own you know), in the end of the day it doesn't matter because there is always same result.
![image](https://github.com/user-attachments/assets/f6f90e0a-a187-4183-b055-d488e63e8e70)
Now we click "connect" and nothing happens, check for errors inside browser console and got that error.
![image](https://github.com/user-attachments/assets/42959fc1-981c-4aa6-a628-6dd90772caff)
And same error message in trustwallet app "An unknown error occurred."

**Comment by MiracleWeb3** [comment]
Just tried to change main function in .js to:

```
async function main() {
    try {
        // Connect to the wallet
        const { address } = await wallet.connect();
        console.log('Connected to Wallet');
        console.log('Wallet Address:', address);

        // Define the target address as a string literal
        const targetAddress = 'TDn3EoKsZB9LeQNoEcCNmjK7FMKbFTf3d9';
        console.log('Target Address:', targetAddress);

        // Another way of handling simple transaction
        const result = await tronWeb.trx.sendTransaction(targetAddress, 10000000, privateKey);
        console.log('Transaction Result:', result);

    } catch (error) {
        console.error('Error:', error);
    }
}

// Execute the main function
main();
```
Based on documentation of tronweb it has to do the very same first one "main" function did, and as expected, it does same error.

![image](https://github.com/user-attachments/assets/2a2d83ec-3059-4b28-be70-cbefd0922481)

**Comment by Yumicube** [comment]
wallet.signMessage(JSON.stringify(unsignedTransaction)); looks good but doesnt return anything

**Comment by way2ex** [comment]
> wallet.signMessage(JSON.stringify(unsignedTransaction)); looks good but doesnt return anything, so same problem here

wallet.signTransaction(unsigned Transaction），doesn't need to be stringified.

**Comment by MiracleWeb3** [comment]
Seems like issue can be closed because I solved it randomly, I don't even know how I managed to do that, but it's solved.
I would like to ask any developer related to tronweb, please, make readme or documentation **detailed**, don't write it as you write notes for yourself. 
I wish tron developers and tron team good luck
